name: 📚 Documentation
description: Report incorrect or missing documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!
        
  - type: dropdown
    id: type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect documentation
        - Unclear documentation
        - Typo or grammar issue
        - Outdated documentation
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation located? (URL or file path)
      placeholder: e.g., README.md or docs/getting-started.md
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Documentation
      description: What does the current documentation say (if applicable)?
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Suggested Improvement
      description: What should the documentation say instead?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the documentation issue here.
    validations:
      required: false
